module.exports = [
  { username: "aarav.sharma", plainPassword: "SB@1001", name: "Aarav Sharma", email: "aarav.sharma@skillbase.in", phone: "9000001001", age: 28, expertise: ["electrician", "wiring", "switch repair"] },
  { username: "vivaan.patel", plainPassword: "SB@1002", name: "Vivaan Patel", email: "vivaan.patel@skillbase.in", phone: "9000001002", age: 31, expertise: ["tv repair", "led tv", "home appliances"] },
  { username: "aditya.reddy", plainPassword: "SB@1003", name: "Aditya Reddy", email: "aditya.reddy@skillbase.in", phone: "9000001003", age: 29, expertise: ["ac repair", "cooling system", "gas refill"] },
  { username: "krishna.nair", plainPassword: "SB@1004", name: "Krishna Nair", email: "krishna.nair@skillbase.in", phone: "9000001004", age: 34, expertise: ["fan repair", "motor repair", "electrician"] },
  { username: "rohan.verma", plainPassword: "SB@1005", name: "Rohan Verma", email: "rohan.verma@skillbase.in", phone: "9000001005", age: 27, expertise: ["fridge repair", "compressor", "cooling system"] },
  { username: "arjun.iyer", plainPassword: "SB@1006", name: "Arjun Iyer", email: "arjun.iyer@skillbase.in", phone: "9000001006", age: 33, expertise: ["washing machine", "motor repair", "pipe fixing"] },
  { username: "siddharth.singh", plainPassword: "SB@1007", name: "Siddharth Singh", email: "siddharth.singh@skillbase.in", phone: "9000001007", age: 30, expertise: ["mixer repair", "kitchen appliances", "electrician"] },
  { username: "rahul.chauhan", plainPassword: "SB@1008", name: "Rahul Chauhan", email: "rahul.chauhan@skillbase.in", phone: "9000001008", age: 32, expertise: ["inverter repair", "battery service", "wiring"] },
  { username: "manav.gupta", plainPassword: "SB@1009", name: "Manav Gupta", email: "manav.gupta@skillbase.in", phone: "9000001009", age: 26, expertise: ["geyser repair", "heating system", "plumbing"] },
  { username: "harshit.yadav", plainPassword: "SB@1010", name: "Harshit Yadav", email: "harshit.yadav@skillbase.in", phone: "9000001010", age: 35, expertise: ["water purifier", "filter service", "pipe fixing"] },
  { username: "priya.mehta", plainPassword: "SB@1011", name: "Priya Mehta", email: "priya.mehta@skillbase.in", phone: "9000001011", age: 27, expertise: ["electrician", "wiring", "home appliances"] },
  { username: "ananya.kulkarni", plainPassword: "SB@1012", name: "Ananya Kulkarni", email: "ananya.kulkarni@skillbase.in", phone: "9000001012", age: 29, expertise: ["tv repair", "set top box", "remote service"] },
  { username: "isha.joshi", plainPassword: "SB@1013", name: "Isha Joshi", email: "isha.joshi@skillbase.in", phone: "9000001013", age: 30, expertise: ["ac repair", "cooling system", "installation"] },
  { username: "kavya.menon", plainPassword: "SB@1014", name: "Kavya Menon", email: "kavya.menon@skillbase.in", phone: "9000001014", age: 31, expertise: ["washing machine", "dryer", "motor repair"] },
  { username: "neha.bansal", plainPassword: "SB@1015", name: "Neha Bansal", email: "neha.bansal@skillbase.in", phone: "9000001015", age: 28, expertise: ["fridge repair", "deep freezer", "cooling system"] },
  { username: "sneha.pillai", plainPassword: "SB@1016", name: "Sneha Pillai", email: "sneha.pillai@skillbase.in", phone: "9000001016", age: 33, expertise: ["mixer repair", "kitchen appliances", "fan repair"] },
  { username: "pooja.shetty", plainPassword: "SB@1017", name: "Pooja Shetty", email: "pooja.shetty@skillbase.in", phone: "9000001017", age: 34, expertise: ["water purifier", "geyser repair", "pipe fixing"] },
  { username: "meera.mishra", plainPassword: "SB@1018", name: "Meera Mishra", email: "meera.mishra@skillbase.in", phone: "9000001018", age: 26, expertise: ["electrician", "switch repair", "inverter repair"] },
  { username: "nisha.agarwal", plainPassword: "SB@1019", name: "Nisha Agarwal", email: "nisha.agarwal@skillbase.in", phone: "9000001019", age: 32, expertise: ["fan repair", "motor repair", "wiring"] },
  { username: "sushmita.das", plainPassword: "SB@1020", name: "Sushmita Das", email: "sushmita.das@skillbase.in", phone: "9000001020", age: 29, expertise: ["tv repair", "speaker repair", "home appliances"] },
  { username: "lakshmi.narayan", plainPassword: "SB@1021", name: "Lakshmi Narayan", email: "lakshmi.narayan@skillbase.in", phone: "9000001021", age: 36, expertise: ["ac repair", "ventilation", "gas refill"] },
  { username: "deepak.malhotra", plainPassword: "SB@1022", name: "Deepak Malhotra", email: "deepak.malhotra@skillbase.in", phone: "9000001022", age: 38, expertise: ["electrician", "mcb repair", "wiring"] },
  { username: "nitin.saxena", plainPassword: "SB@1023", name: "Nitin Saxena", email: "nitin.saxena@skillbase.in", phone: "9000001023", age: 30, expertise: ["washing machine", "dryer", "pipe fixing"] },
  { username: "mukesh.tiwari", plainPassword: "SB@1024", name: "Mukesh Tiwari", email: "mukesh.tiwari@skillbase.in", phone: "9000001024", age: 39, expertise: ["fridge repair", "compressor", "cooling system"] },
  { username: "sunil.tripathi", plainPassword: "SB@1025", name: "Sunil Tripathi", email: "sunil.tripathi@skillbase.in", phone: "9000001025", age: 35, expertise: ["geyser repair", "heating system", "electrician"] },
  { username: "amitabh.pandey", plainPassword: "SB@1026", name: "Amitabh Pandey", email: "amitabh.pandey@skillbase.in", phone: "9000001026", age: 37, expertise: ["water purifier", "filter service", "plumbing"] },
  { username: "rajesh.khanna", plainPassword: "SB@1027", name: "Rajesh Khanna", email: "rajesh.khanna@skillbase.in", phone: "9000001027", age: 41, expertise: ["mixer repair", "kitchen appliances", "switch repair"] },
  { username: "vikram.jeet", plainPassword: "SB@1028", name: "Vikram Jeet", email: "vikram.jeet@skillbase.in", phone: "9000001028", age: 29, expertise: ["tv repair", "remote service", "wiring"] },
  { username: "anil.kumar", plainPassword: "SB@1029", name: "Anil Kumar", email: "anil.kumar@skillbase.in", phone: "9000001029", age: 33, expertise: ["inverter repair", "battery service", "home appliances"] },
  { username: "sandeep.rana", plainPassword: "SB@1030", name: "Sandeep Rana", email: "sandeep.rana@skillbase.in", phone: "9000001030", age: 28, expertise: ["fan repair", "motor repair", "electrician"] },
  { username: "divya.naidu", plainPassword: "SB@1031", name: "Divya Naidu", email: "divya.naidu@skillbase.in", phone: "9000001031", age: 27, expertise: ["ac repair", "installation", "cooling system"] },
  { username: "ritu.arora", plainPassword: "SB@1032", name: "Ritu Arora", email: "ritu.arora@skillbase.in", phone: "9000001032", age: 30, expertise: ["fridge repair", "deep freezer", "compressor"] },
  { username: "komal.singla", plainPassword: "SB@1033", name: "Komal Singla", email: "komal.singla@skillbase.in", phone: "9000001033", age: 31, expertise: ["washing machine", "motor repair", "kitchen appliances"] },
  { username: "bhavna.sood", plainPassword: "SB@1034", name: "Bhavna Sood", email: "bhavna.sood@skillbase.in", phone: "9000001034", age: 26, expertise: ["geyser repair", "plumbing", "pipe fixing"] },
  { username: "farah.khan", plainPassword: "SB@1035", name: "Farah Khan", email: "farah.khan@skillbase.in", phone: "9000001035", age: 33, expertise: ["tv repair", "speaker repair", "mixer repair"] },
  { username: "shalini.saxena", plainPassword: "SB@1036", name: "Shalini Saxena", email: "shalini.saxena@skillbase.in", phone: "9000001036", age: 29, expertise: ["electrician", "switch repair", "wiring"] },
  { username: "hema.rao", plainPassword: "SB@1037", name: "Hema Rao", email: "hema.rao@skillbase.in", phone: "9000001037", age: 34, expertise: ["water purifier", "filter service", "installation"] },
  { username: "nandini.rai", plainPassword: "SB@1038", name: "Nandini Rai", email: "nandini.rai@skillbase.in", phone: "9000001038", age: 28, expertise: ["fan repair", "electrician", "home appliances"] },
  { username: "tanya.sethi", plainPassword: "SB@1039", name: "Tanya Sethi", email: "tanya.sethi@skillbase.in", phone: "9000001039", age: 32, expertise: ["ac repair", "gas refill", "ventilation"] },
  { username: "swati.chopra", plainPassword: "SB@1040", name: "Swati Chopra", email: "swati.chopra@skillbase.in", phone: "9000001040", age: 30, expertise: ["fridge repair", "cooling system", "inverter repair"] },
  { username: "sakshi.goyal", plainPassword: "SB@1041", name: "Sakshi Goyal", email: "sakshi.goyal@skillbase.in", phone: "9000001041", age: 27, expertise: ["washing machine", "dryer", "motor repair"] },
  { username: "monika.jain", plainPassword: "SB@1042", name: "Monika Jain", email: "monika.jain@skillbase.in", phone: "9000001042", age: 35, expertise: ["electrician", "mcb repair", "inverter repair"] },
  { username: "geeta.kapoor", plainPassword: "SB@1043", name: "Geeta Kapoor", email: "geeta.kapoor@skillbase.in", phone: "9000001043", age: 36, expertise: ["geyser repair", "water purifier", "heating system"] },
  { username: "rekha.madan", plainPassword: "SB@1044", name: "Rekha Madan", email: "rekha.madan@skillbase.in", phone: "9000001044", age: 31, expertise: ["tv repair", "set top box", "remote service"] },
  { username: "poonam.dua", plainPassword: "SB@1045", name: "Poonam Dua", email: "poonam.dua@skillbase.in", phone: "9000001045", age: 29, expertise: ["mixer repair", "kitchen appliances", "fan repair"] },
  { username: "renu.sarin", plainPassword: "SB@1046", name: "Renu Sarin", email: "renu.sarin@skillbase.in", phone: "9000001046", age: 33, expertise: ["electrician", "switch repair", "home appliances"] },
  { username: "sarita.pal", plainPassword: "SB@1047", name: "Sarita Pal", email: "sarita.pal@skillbase.in", phone: "9000001047", age: 28, expertise: ["water purifier", "pipe fixing", "plumbing"] },
  { username: "usha.rawat", plainPassword: "SB@1048", name: "Usha Rawat", email: "usha.rawat@skillbase.in", phone: "9000001048", age: 37, expertise: ["ac repair", "installation", "cooling system"] },
  { username: "sangeeta.roy", plainPassword: "SB@1049", name: "Sangeeta Roy", email: "sangeeta.roy@skillbase.in", phone: "9000001049", age: 34, expertise: ["fridge repair", "compressor", "cooling system"] },
  { username: "susheela.kumari", plainPassword: "SB@1050", name: "Susheela Kumari", email: "susheela.kumari@skillbase.in", phone: "9000001050", age: 32, expertise: ["electrician", "tv repair", "fan repair"] },
];
